### PR TITLE
Pull changes from original repo

### PR DESCRIPTION
**Pull request by anx-ckreuzberger**

### CODE REVIEW

**Comment by fahadm** [comment]
I see that you have still have `4b08e12d5bccc9a63c51b8624286ca32a9a63393`  in your  `htmlparams2` branch, this breaks the `scope` param in the `getString` method. Is it still required now that you have rebased on the latest rubenv/master and it has the commit `ba72a470959e45828ae3acb1e3f3337d58e41e13` which I presume is the solution for the same thing without breaking `getString` scope.

I am sorry for having to write this here as I was unable to find an email address or an issue board.

**Comment by anx-ckreuzberger** [comment]
Thanks for the heads up.

I wanted to update this repo to the latest version of rubenv:master. The htmlparams2 branch was used for adding additional functionality (related to the scope param in getString). 

I guess `4b08e12d5bccc9a63c51b8624286ca32a9a63393` is a duplicate of `ba72a470959e45828ae3acb1e3f3337d58e41e13` and therefore it needs to be removed?

**Comment by fahadm** [comment]
Yea, I think so in the `htmlparams2` branch, you are the author of both of those commits so you should know better.

I was using your `htmlparams2` branch and all my `getString` with a `scope` stopped working, even though all the method calls were working on `gettext 2.4.1`, (I tested for any XSS that might still be possible wasn't able to find any even when using scope variables as I believe `ba72a470959e45828ae3acb1e3f3337d58e41e13` fixed that.)

Thank you for replying though.

**Comment by anx-ckreuzberger** [comment]
I'll should be able to fix this.

Would it work for you to use the original source from rubenv/master?  https://github.com/rubenv/angular-gettext
It should contain the security fixes, but it doesn't contain my `html-params-*` extension.

**Comment by fahadm** [comment]
I would, but I need to use the `html-params-*` extension. 

Right now I am working off a fork of `html-params-*` with `4b08e12d5bccc9a63c51b8624286ca32a9a63393 `  reverted, but I would be very grateful if you can somehow get `html-params-*` changes up-streamed. I would be willing to provide any assistance you might need.

**Comment by anx-ckreuzberger** [comment]
Hi,

I've just tested it, and I can confirm
```javascript
        console.log(gettextCatalog.getString("Hello World, my name is {{name}}", {name: "bla"}));
```
is outputting `Hello World, my name is {{name}}` rather than `Hello World, my name is bla`.

I've created the branch htmlparams2-remastered, where I removed the aforementioned commit. The example above does now work correctly, and I'll clean up and move the content of that branch to the htmlparams2 branch.

Thank you for the report!

**Comment by anx-ckreuzberger** [comment]
Interesting enough, there is a series of tests for exactly this behaviour, and they all work (locally and in the CI):

https://github.com/anx-ckreuzberger/angular-gettext/blob/34a0f68a30f31503376dae54641e774032915aca/test/unit/catalog.js#L104-L128

I'll investigate on what is going on here, to prevent such issues at a later point.

**Comment by fahadm** [comment]
You added the tests in [This Pull request](https://github.com/rubenv/angular-gettext/pull/350#pullrequestreview-99980892)

but then changed your implementation after rubenv point this out.  You probably forgot to update the tests in the html params branch :).

**Comment by anx-ckreuzberger** [comment]
I should definately read my own code, you are absolutely right.

I'll get the other branch cleaned and and then I'll update this branch - and I'll create a tag/version for it, so we can reference it in the future.

Thanks for all the help!

**Pull request merged**
